### ISSUE TITLE
doesn't start after upgrade

### ISSUE THREAD

**Issue by adocampo** [Nukesor/archivebot#21]
Today I've git pulled the latest version and now archivebot isn't starting.
After the `git pull`command, I ran `make`and it upgraded some dependencies

The error is
```
poetry run ./main.py
Traceback (most recent call last):
File "./main.py", line 3, in <module>
from archivebot.archivebot import main
File "/data/scripts/telegram/archivebot/archivebot/archivebot.py", line 8, in <module>
from archivebot.config import config
File "/data/scripts/telegram/archivebot/archivebot/config.py", line 38, in <module>
if option not in config[key]:
KeyError: 'zip'
```

Any ideas?

**Comment by Nukesor** [comment]
A new option has been added and there was a bug in the newly added default configuration logic.

Should be fixed by now.

**Comment by adocampo** [comment]
Yes, is working again.
Thank you! :D
